fragment a on Node { id 
    ...on User {
                bio, company, pronouns, isDeveloperProgramMember, isEmployee, updatedAt,
                projects(first:10) {
                    edges { node { id } } }, 
                repositories(first:10) {
                    edges { node { id } } }, 
                repositoriesContributedTo(first:10) {
                    edges { node { id } } }, 
                organizations(first:10) { 
                    edges { node { description } } 
                },
                socialAccounts(first:10) { 
                    edges { node { url } } 
                },
    }
}